export default [
  {
    title: '中国国旗',
    path: 'stillness/FlagChina',
    name: 'FlagChina',
    component: () => import('@/views/page/stillness/FlagChina.vue'),
  },
  {
    title: '中国象棋棋盘',
    path: 'stillness/ChineseChessBoard',
    name: 'ChineseChessBoard',
    component: () => import('@/views/page/stillness/ChineseChessBoard.vue'),
  },
  {
    title: '硬笔练习纸',
    path: 'stillness/PenExercisePaper',
    name: 'PenExercisePaper',
    component: () => import('@/views/page/stillness/PenExercisePaper.vue'),
  },
  {
    title: '旋转八卦图',
    path: 'animation/EightDiagrams',
    name: 'EightDiagrams',
    component: () => import('@/views/page/animation/EightDiagrams.vue'),
  },
  {
    title: '围棋',
    path: 'game/ChineseGo',
    name: 'ChineseGo',
    component: () => import('@/views/page/game/ChineseGo.vue'),
  },
  {
    title: '乱撞的小球',
    path: 'animation/RunnerBall',
    name: 'RunnerBall',
    component: () => import('@/views/page/animation/RunnerBall.vue'),
  },
  {
    title: '彩色微粒',
    path: 'animation/ColorParticle',
    name: 'ColorParticle',
    component: () => import('@/views/page/animation/ColorParticle.vue'),
  },
  {
    title: '散漫的小球',
    path: 'animation/DesultoryBall',
    name: 'DesultoryBall',
    component: () => import('@/views/page/animation/DesultoryBall.vue'),
  },
  {
    title: '随机射线',
    path: 'animation/RandomRadial',
    name: 'RandomRadial',
    component: () => import('@/views/page/animation/RandomRadial.vue'),
  },
  {
    title: '字母变换',
    path: 'animation/LetterTransform',
    name: 'LetterTransform',
    component: () => import('@/views/page/animation/LetterTransform.vue'),
  },
  {
    title: '颜色转盘',
    path: 'animation/ColorTurntable',
    name: 'ColorTurntable',
    component: () => import('@/views/page/animation/ColorTurntable.vue'),
  },
  {
    title: '象棋',
    path: 'game/ChineseChess',
    name: 'ChineseChess',
    component: () => import('@/views/page/game/ChineseChess.vue'),
  },
  {
    title: '星空背景',
    path: 'animation/Starry',
    name: 'Starry',
    component: () => import('@/views/page/animation/Starry.vue'),
  },
  {
    title: '七巧板动画',
    path: 'animation/SevenPiecePuzzleAnimation',
    name: 'SevenPiecePuzzleAnimation',
    component: () => import('@/views/page/animation/SevenPiecePuzzleAnimation.vue'),
  },
];
