export default [
  {
    title: '中国国旗',
    path: 'stillness/FlagChina',
    name: 'FlagChina',
    component: () => import('@/views/page/stillness/FlagChina.vue'),
  },
  {
    title: '中国象棋棋盘',
    path: 'stillness/ChineseChessBoard',
    name: 'ChineseChessBoard',
    component: () => import('@/views/page/stillness/ChineseChessBoard.vue'),
  },
  {
    title: '硬笔练习纸',
    path: 'stillness/PenExercisePaper',
    name: 'PenExercisePaper',
    component: () => import('@/views/page/stillness/PenExercisePaper.vue'),
  },
  {
    title: '旋转八卦图',
    path: 'animation/EightDiagrams',
    name: 'EightDiagrams',
    component: () => import('@/views/page/animation/EightDiagrams.vue'),
  },
  {
    title: '围棋',
    path: 'game/ChineseGo',
    name: 'ChineseGo',
    component: () => import('@/views/page/game/ChineseGo.vue'),
  },
  {
    title: '乱撞的小球',
    path: 'background/RunnerBall',
    name: 'RunnerBall',
    component: () => import('@/views/page/background/RunnerBall.vue'),
  },
  {
    title: '彩色微粒',
    path: 'background/ColorParticle',
    name: 'ColorParticle',
    component: () => import('@/views/page/background/ColorParticle.vue'),
  },
  {
    title: '散漫的小球',
    path: 'background/DesultoryBall',
    name: 'DesultoryBall',
    component: () => import('@/views/page/background/DesultoryBall.vue'),
  },
  {
    title: '随机射线',
    path: 'background/RandomRadial',
    name: 'RandomRadial',
    component: () => import('@/views/page/background/RandomRadial.vue'),
  },
  {
    title: '字母变换',
    path: 'animation/LetterTransform',
    name: 'LetterTransform',
    component: () => import('@/views/page/animation/LetterTransform.vue'),
  },
  {
    title: '颜色转盘',
    path: 'animation/ColorTurntable',
    name: 'ColorTurntable',
    component: () => import('@/views/page/animation/ColorTurntable.vue'),
  },
  // {
  //   title: '象棋',
  //   path: 'game/ChineseChess',
  //   name: 'ChineseChess',
  //   component: () => import('@/views/page/game/ChineseChess.vue'),
  // },
  {
    title: '星空背景',
    path: 'background/Starry',
    name: 'Starry',
    component: () => import('@/views/page/background/Starry.vue'),
  },
  {
    title: '七巧板动画',
    path: 'animation/SevenPiecePuzzleAnimation',
    name: 'SevenPiecePuzzleAnimation',
    component: () => import('@/views/page/animation/SevenPiecePuzzleAnimation.vue'),
  },
  {
    title: '激光特效',
    path: 'background/LaserEffect',
    name: 'LaserEffect',
    component: () => import('@/views/page/background/LaserEffect.vue'),
  },
  {
    title: '华容道',
    path: 'game/HuaRongRoad',
    name: 'HuaRongRoad',
    component: () => import('@/views/page/game/HuaRongRoad.vue'),
  },
  {
    title: '几何颗粒动画',
    path: 'background/GeometricParticle',
    name: 'GeometricParticle',
    component: () => import('@/views/page/background/GeometricParticle.vue'),
  },
  {
    title: '数字华容道',
    path: 'game/DigitalHuarongRoad',
    name: 'DigitalHuarongRoad',
    component: () => import('@/views/page/game/DigitalHuarongRoad.vue'),
  },
  {
    title: '新年倒计时',
    path: 'background/NewYearCountdown',
    name: 'NewYearCountdown',
    component: () => import('@/views/page/background/NewYearCountdown.vue'),
  },
  {
    title: '贪吃蛇',
    path: 'game/GluttonousSnake',
    name: 'GluttonousSnake',
    component: () => import('@/views/page/game/GluttonousSnake.vue'),
  },
  {
    title: '彩色烟花动画',
    path: 'animation/ColorFireworks',
    name: 'ColorFireworks',
    component: () => import('@/views/page/animation/ColorFireworks.vue'),
  },
  {
    title: '旋转线条动画',
    path: 'animation/RotateLineAnimation',
    name: 'RotateLineAnimation',
    component: () => import('@/views/page/animation/RotateLineAnimation.vue'),
  },
  {
    title: '彩色旋转线条',
    path: 'animation/ColoredRotatingLines',
    name: 'ColoredRotatingLines',
    component: () => import('@/views/page/animation/ColoredRotatingLines.vue'),
  },
  {
    title: '小木人动画',
    path: 'animation/WoodenManAnimation',
    name: 'WoodenManAnimation',
    component: () => import('@/views/page/animation/WoodenManAnimation.vue'),
  },
  {
    title: '加载动画1',
    path: 'animation/LoadingAnimation1',
    name: 'LoadingAnimation1',
    component: () => import('@/views/page/animation/LoadingAnimation1.vue'),
  },
  {
    title: '旋转构建动画1',
    path: 'animation/RotateConstructionAnimation1',
    name: 'RotateConstructionAnimation1',
    component: () => import('@/views/page/animation/RotateConstructionAnimation1.vue'),
  },
  {
    title: '旋转构建动画2',
    path: 'animation/RotateConstructionAnimation2',
    name: 'RotateConstructionAnimation2',
    component: () => import('@/views/page/animation/RotateConstructionAnimation2.vue'),
  },
  {
    title: '单摆运动',
    path: 'animation/SimplePendulumAnimation',
    name: 'SimplePendulumAnimation',
    component: () => import('@/views/page/animation/SimplePendulumAnimation.vue'),
  },
  {
    title: '心形动画1',
    path: 'animation/CardioidAnimation1',
    name: 'CardioidAnimation1',
    component: () => import('@/views/page/animation/CardioidAnimation1.vue'),
  },
  {
    title: '旋转构建动画3',
    path: 'animation/RotateConstructionAnimation3',
    name: 'RotateConstructionAnimation3',
    component: () => import('@/views/page/animation/RotateConstructionAnimation3.vue'),
  },
  {
    title: '心形动画2',
    path: 'animation/CardioidAnimation2',
    name: 'CardioidAnimation2',
    component: () => import('@/views/page/animation/CardioidAnimation2.vue'),
  }
];
