export default [
  {
    title: '中国国旗',
    path: 'stillness/FlagChina',
    name: 'FlagChina',
    component: () => import('@/views/page/stillness/FlagChina.vue'),
  },
  {
    title: '中国象棋棋盘',
    path: 'stillness/ChineseChessBoard',
    name: 'ChineseChessBoard',
    component: () => import('@/views/page/stillness/ChineseChessBoard.vue'),
  },
  {
    title: '硬笔练习纸',
    path: 'stillness/PenExercisePaper',
    name: 'PenExercisePaper',
    component: () => import('@/views/page/stillness/PenExercisePaper.vue'),
  },
  {
    title: '旋转八卦图',
    path: 'animation/EightDiagrams',
    name: 'EightDiagrams',
    component: () => import('@/views/page/animation/EightDiagrams.vue'),
  },
  {
    title: '围棋',
    path: 'game/ChineseGo',
    name: 'ChineseGo',
    component: () => import('@/views/page/game/ChineseGo.vue'),
  },
  {
    title: '乱撞的小球',
    path: 'background/RunnerBall',
    name: 'RunnerBall',
    component: () => import('@/views/page/background/RunnerBall.vue'),
  },
  {
    title: '彩色微粒',
    path: 'background/ColorParticle',
    name: 'ColorParticle',
    component: () => import('@/views/page/background/ColorParticle.vue'),
  },
  {
    title: '散漫的小球',
    path: 'background/DesultoryBall',
    name: 'DesultoryBall',
    component: () => import('@/views/page/background/DesultoryBall.vue'),
  },
  {
    title: '随机射线',
    path: 'background/RandomRadial',
    name: 'RandomRadial',
    component: () => import('@/views/page/background/RandomRadial.vue'),
  },
  {
    title: '字母变换',
    path: 'animation/LetterTransform',
    name: 'LetterTransform',
    component: () => import('@/views/page/animation/LetterTransform.vue'),
  },
  {
    title: '颜色转盘',
    path: 'animation/ColorTurntable',
    name: 'ColorTurntable',
    component: () => import('@/views/page/animation/ColorTurntable.vue'),
  },
  // {
  //   title: '象棋',
  //   path: 'game/ChineseChess',
  //   name: 'ChineseChess',
  //   component: () => import('@/views/page/game/ChineseChess.vue'),
  // },
  {
    title: '星空背景',
    path: 'background/Starry',
    name: 'Starry',
    component: () => import('@/views/page/background/Starry.vue'),
  },
  {
    title: '七巧板动画',
    path: 'animation/SevenPiecePuzzleAnimation',
    name: 'SevenPiecePuzzleAnimation',
    component: () => import('@/views/page/animation/SevenPiecePuzzleAnimation.vue'),
  },
  {
    title: '激光特效',
    path: 'background/LaserEffect',
    name: 'LaserEffect',
    component: () => import('@/views/page/background/LaserEffect.vue'),
  },
  {
    title: '华容道',
    path: 'game/HuaRongRoad',
    name: 'HuaRongRoad',
    component: () => import('@/views/page/game/HuaRongRoad.vue'),
  },
  {
    title: '几何颗粒动画',
    path: 'background/GeometricParticle',
    name: 'GeometricParticle',
    component: () => import('@/views/page/background/GeometricParticle.vue'),
  },
  {
    title: '数字华容道',
    path: 'game/DigitalHuarongRoad',
    name: 'DigitalHuarongRoad',
    component: () => import('@/views/page/game/DigitalHuarongRoad.vue'),
  },
  {
    title: '新年倒计时',
    path: 'background/NewYearCountdown',
    name: 'NewYearCountdown',
    component: () => import('@/views/page/background/NewYearCountdown.vue'),
  },
  {
    title: '贪吃蛇',
    path: 'game/GluttonousSnake',
    name: 'GluttonousSnake',
    component: () => import('@/views/page/game/GluttonousSnake.vue'),
  },
  {
    title: '彩色烟花动画',
    path: 'animation/ColorFireworks',
    name: 'ColorFireworks',
    component: () => import('@/views/page/animation/ColorFireworks.vue'),
  },
  {
    title: '旋转线条动画',
    path: 'animation/RotateLineAnimation',
    name: 'RotateLineAnimation',
    component: () => import('@/views/page/animation/RotateLineAnimation.vue'),
  },
  {
    title: '彩色旋转线条',
    path: 'animation/ColoredRotatingLines',
    name: 'ColoredRotatingLines',
    component: () => import('@/views/page/animation/ColoredRotatingLines.vue'),
  },
  {
    title: '小木人动画',
    path: 'animation/WoodenManAnimation',
    name: 'WoodenManAnimation',
    component: () => import('@/views/page/animation/WoodenManAnimation.vue'),
  },
  {
    title: '加载动画1',
    path: 'animation/LoadingAnimation1',
    name: 'LoadingAnimation1',
    component: () => import('@/views/page/animation/LoadingAnimation1.vue'),
  },
  {
    title: '旋转构建动画1',
    path: 'animation/RotateConstructionAnimation1',
    name: 'RotateConstructionAnimation1',
    component: () => import('@/views/page/animation/RotateConstructionAnimation1.vue'),
  },
  {
    title: '旋转构建动画2',
    path: 'animation/RotateConstructionAnimation2',
    name: 'RotateConstructionAnimation2',
    component: () => import('@/views/page/animation/RotateConstructionAnimation2.vue'),
  },
  {
    title: '单摆运动',
    path: 'animation/SimplePendulumAnimation',
    name: 'SimplePendulumAnimation',
    component: () => import('@/views/page/animation/SimplePendulumAnimation.vue'),
  },
  {
    title: '心形动画1',
    path: 'animation/CardioidAnimation1',
    name: 'CardioidAnimation1',
    component: () => import('@/views/page/animation/CardioidAnimation1.vue'),
  },
  {
    title: '旋转构建动画3',
    path: 'animation/RotateConstructionAnimation3',
    name: 'RotateConstructionAnimation3',
    component: () => import('@/views/page/animation/RotateConstructionAnimation3.vue'),
  },
  {
    title: '心形动画2',
    path: 'animation/CardioidAnimation2',
    name: 'CardioidAnimation2',
    component: () => import('@/views/page/animation/CardioidAnimation2.vue'),
  },
  {
    title: '视觉误差图1',
    path: 'stillness/VisualErrorImage1',
    name: 'VisualErrorImage1',
    component: () => import('@/views/page/stillness/VisualErrorImage1.vue'),
  },
  {
    title: '旋转构建动画4',
    path: 'animation/RotateConstructionAnimation4',
    name: 'RotateConstructionAnimation4',
    component: () => import('@/views/page/animation/RotateConstructionAnimation4.vue'),
  },
  {
    title: '色彩版',
    path: 'stillness/ColorBoard',
    name: 'ColorBoard',
    component: () => import('@/views/page/stillness/ColorBoard.vue'),
  },
  {
    title: '视觉误差动画1',
    path: 'animation/VisualErrorAnimation1',
    name: 'VisualErrorAnimation1',
    component: () => import('@/views/page/animation/VisualErrorAnimation1.vue'),
  },
  {
    title: '旋转构建动画5',
    path: 'animation/RotateConstructionAnimation5',
    name: 'RotateConstructionAnimation5',
    component: () => import('@/views/page/animation/RotateConstructionAnimation5.vue'),
  },
  {
    title: '祥云花纹',
    path: 'stillness/AuspiciousCloudPattern',
    name: 'AuspiciousCloudPattern',
    component: () => import('@/views/page/stillness/AuspiciousCloudPattern.vue'),
  },
  {
    title: '旋转构建动画6',
    path: 'animation/RotateConstructionAnimation6',
    name: 'RotateConstructionAnimation6',
    component: () => import('@/views/page/animation/RotateConstructionAnimation6.vue'),
  },
  {
    title: '旋转构建动画7',
    path: 'animation/RotateConstructionAnimation7',
    name: 'RotateConstructionAnimation7',
    component: () => import('@/views/page/animation/RotateConstructionAnimation7.vue'),
  },
  {
    title: '木制花纹1',
    path: 'stillness/WoodenPatterns1',
    name: 'WoodenPatterns1',
    component: () => import('@/views/page/stillness/WoodenPatterns1.vue'),
  },
  {
    title: '分形图1',
    path: 'animation/FractalImage1',
    name: 'FractalImage1',
    component: () => import('@/views/page/animation/FractalImage1.vue'),
  },
  {
    title: '下雨动画',
    path: 'background/RainAnimation',
    name: 'RainAnimation',
    component: () => import('@/views/page/background/RainAnimation.vue'),
  },
  {
    title: '旋转构建动画8',
    path: 'animation/RotateConstructionAnimation8',
    name: 'RotateConstructionAnimation8',
    component: () => import('@/views/page/animation/RotateConstructionAnimation8.vue'),
  },
  {
    title: '静态背景图1',
    path: 'stillness/Background1',
    name: 'StaticBackground1',
    component: () => import('@/views/page/stillness/Background1.vue'),
  },
  {
    title: '旋转构建动画9',
    path: 'animation/RotateConstructionAnimation9',
    name: 'RotateConstructionAnimation9',
    component: () => import('@/views/page/animation/RotateConstructionAnimation9.vue'),
  },
  {
    title: '静态背景图2',
    path: 'stillness/Background2',
    name: 'StaticBackground2',
    component: () => import('@/views/page/stillness/Background2.vue'),
  },
  {
    title: '心形动画3',
    path: 'animation/CardioidAnimation3',
    name: 'CardioidAnimation3',
    component: () => import('@/views/page/animation/CardioidAnimation3.vue'),
  },
  {
    title: '分形图2',
    path: 'animation/FractalImage2',
    name: 'FractalImage2',
    component: () => import('@/views/page/animation/FractalImage2.vue'),
  },
  {
    title: '静态背景图3',
    path: 'stillness/Background3',
    name: 'StaticBackground3',
    component: () => import('@/views/page/stillness/Background3.vue'),
  },
  {
    title: '静态背景图4',
    path: 'stillness/Background4',
    name: 'StaticBackground4',
    component: () => import('@/views/page/stillness/Background4.vue'),
  },
  {
    title: '分形图3',
    path: 'animation/FractalImage3',
    name: 'FractalImage3',
    component: () => import('@/views/page/animation/FractalImage3.vue'),
  },
  {
    title: '静态背景图5',
    path: 'stillness/Background5',
    name: 'StaticBackground5',
    component: () => import('@/views/page/stillness/Background5.vue'),
  },
  {
    title: '静态背景图6',
    path: 'stillness/Background6',
    name: 'StaticBackground6',
    component: () => import('@/views/page/stillness/Background6.vue'),
  },
  {
    title: '分形图4',
    path: 'animation/FractalImage4',
    name: 'FractalImage4',
    component: () => import('@/views/page/animation/FractalImage4.vue'),
  },
  {
    title: '旋转构建动画10',
    path: 'animation/RotateConstructionAnimation10',
    name: 'RotateConstructionAnimation10',
    component: () => import('@/views/page/animation/RotateConstructionAnimation10.vue'),
  },
  {
    title: '静态背景图7',
    path: 'stillness/Background7',
    name: 'StaticBackground7',
    component: () => import('@/views/page/stillness/Background7.vue'),
  },
  {
    title: '彩虹糖动画',
    path: 'animation/RainbowCandyAnimation',
    name: 'RainbowCandyAnimation',
    component: () => import('@/views/page/animation/RainbowCandyAnimation.vue'),
  },
  {
    title: '静态背景图8',
    path: 'stillness/Background8',
    name: 'StaticBackground8',
    component: () => import('@/views/page/stillness/Background8.vue'),
  }
];
